repo:
  org: organization
  name: organization/repo
  branches:
    main: develop
    release: release
  tag_patterns:
    - name: release
      pattern: "$v"
  labels:
    bugs:
      - bug
    features:
      - enhancement
    security:
      - security
    documentation:
      - documentation
    tech-debt:
      - dependencies
    infrastructure:
      - infrastructure
  special_logins:
    "User 1": user1
  broken_users:
    - user2@test.com
  # filter out users from tracking if they only have old commits
  user_time_filter: False
  clone_url: https://github.com/organization/repo
  folder: repos

google:
  project_id: google-project

influx:
  metric_prefix: github
  auth_token: ""
  endpoint: http://influx
  bucket: bucket1
  org: org1
