name: CI
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"
      - "**/docs/**"

jobs:
  linting:
    name: General File Linting
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Yaml file linting
        run: |
          docker run --rm \
          -v $(pwd):/data \
          cytopia/yamllint \
          -c yamllint.yml -s .

      - name: Pipeline Python Formatting
        run: |
          docker run --rm \
          -v $(pwd):/data \
          cytopia/black \
          --check --diff .

      - name: Pipeline Python Linting
        run: |
          docker run --rm \
          -v $(pwd):/apps \
          alpine/flake8:latest .

      - name: ensure shell scripts are formatted
        run: |
          while IFS= read -r -d '' filename; do
          echo "processing ${filename}"
          docker run --rm -v "$(pwd):/mnt" koalaman/shellcheck:latest -x "${filename}"
          done < <(find . -type f -name "*.sh" ! -path "*/.git/*" -print0)

  build:
    name: build container
    runs-on: self-hosted
    if: "github.ref == 'refs/heads/main'"
    needs:
      - linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get short sha for commit
        id: get-short-sha
        run: |
          echo "::set-output name=short_sha::$(git rev-parse HEAD | cut -c1-8)"
      - name: build/push image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: us-central1-docker.pkg.dev/civic-eagle-enview-dev/github-stat-collector/github-stat-collector:latest,us-central1-docker.pkg.dev/civic-eagle-enview-dev/github-stat-collector/github-stat-collector:${{ steps.get-short-sha.outputs.short_sha }}
          push: true
