name: CI
on:
  push:
    tags:
      - "v*"
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"
      - "**/docs/**"

jobs:
  linting:
    name: General File Linting
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Yaml file linting
        run: |
          docker run --rm \
          -v $(pwd):/data \
          cytopia/yamllint \
          -c yamllint.yml -s .

      - name: Python Formatting
        run: |
          docker run --rm \
          -v $(pwd):/data \
          cytopia/black \
          --check --diff .

      - name: Python Linting
        run: |
          docker run --rm \
          -v $(pwd):/apps \
          alpine/flake8:latest .

      - name: ensure shell scripts are formatted
        run: |
          while IFS= read -r -d '' filename; do
          echo "processing ${filename}"
          docker run --rm -v "$(pwd):/mnt" koalaman/shellcheck:latest -x "${filename}"
          done < <(find . -type f -name "*.sh" ! -path "*/.git/*" -print0)
      - name: Get current tag
        id: get_tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)
    outputs:
      tag: ${{ steps.get_tag.outputs.TAG }}

  deploy:
    name: Deploy package
    needs:
      - linting
    runs-on: self-hosted
    if: "(
         success() &&
         startswith(needs.linting.outputs.tag, 'v')
         )"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build/Deploy
        env:
          DEPLOY_KEY_FILE: ${{ secrets.DEPLOY_KEY_FILE }}
        run: TAG=${{ steps.get_tag.outputs.TAG }} bash util/build.sh
